apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - bookinfo
    labelSelectors:
      'app' : 'reviews'
      'version' : 'v2'
  delay:
    latency: "9090ms"
    correlation: "25"
    jitter: "90ms"
  direction: to
  target:
    selector:
      namespaces:
        - bookinfo
      labelSelectors:
        'app' : 'ratings'
    mode: one
  duration: "50s"
  scheduler:
    cron: "@every 1m"
