apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-example1
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - bookinfo
    labelSelectors:
      'app' : 'ratings'
  scheduler:
    cron: '@every 10s'
